---
- name: Configure hostnames and interface descriptions
  hosts: routers
  gather_facts: no

  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - "hostname {{ device_hostname }}"

    - name: Configure interface description
      ios_config:
        lines:
          - "description {{ interface_description }}"
        parents: interface Ethernet0/0

    - name: Show configured hostname
      ios_command:
        commands:
          - show running-config | include hostname
      register: hostname_output

    - name: Show interface description
      ios_command:
        commands:
          - show interfaces description | include Ethernet0/0
      register: int_output

    - name: Debug output
      debug:
        msg:
          - "{{ hostname_output.stdout_lines }}"
          - "{{ int_output.stdout_lines }}"
